const experiences=[
{name:'深圳优必选科技股份有限公司',en:'UBTECH Robotics',role:'设计 / 解决方案实习生',er:'Design / Solutions Intern',date:'2026.05 — 2026.09',bullets:['参与工业人形机器人数采方案，输出数据采集示意 UI <strong>30+ 张</strong>、具身智能产业学院工程设计方案 <strong>3 次</strong>及专项展示物料 <strong>100+ 项</strong>。','主导产教业务画册与产品内容体系升级，通过流程图、产品架构和场景化展示梳理信息；机器人图鉴获采纳并落地<strong>南山智园优必选展厅</strong>。','承接 CDCC 大会分论坛、EPG 大会等活动，跨部门协同推进主视觉、海报、展板等 <strong>10+ 项</strong>物料交付。'],eb:['Delivered <strong>30+ data collection UI diagrams</strong>, 3 engineering proposals and 100+ presentation assets for embodied intelligence and industry–education projects.','Led the redesign of business brochures and product content. The robot catalog was adopted for the UBTECH showroom at Nanshan Intelligence Park.','Coordinated cross-functional delivery of <strong>10+ visual assets</strong> for CDCC and EPG industry events.'],detail:0},
{name:'特维沃（上海）智能科技有限公司',en:'Teweiwo (Shanghai) Intelligent Technology',role:'人力资源助理',er:'Human Resources Assistant',date:'2025.12 — 2026.02',bullets:['管理人才寻访、简历初筛到面试落地的招聘流程，日均筛选简历 <strong>300+ 份</strong>。','独立担任 <strong>20 余场</strong>初试面试官，推进 <strong>20+ 名</strong>核心岗位候选人进入技术面试，组织各类面试 <strong>50 余场</strong>。'],eb:['Managed sourcing, résumé screening and interview coordination; screened <strong>300+ résumés per day</strong>.','Conducted 20+ initial interviews, advanced 20+ candidates to technical interviews and organized 50+ interviews.'],detail:3},
{name:'安徽木思工业设计有限公司',en:'Anhui Musi Industrial Design',role:'产品设计师',er:'Product Designer',date:'2023.06 — 2025.05',bullets:['负责气模产品全流程设计，从用途、场景、尺寸到造型策划，完成概念草图、手绘稿 <strong>50+ 份</strong>，最终落地量产产品 <strong>10+ 款</strong>。','结合材料与工艺优化产品细节，参与概念发散、草图迭代与造型深化；提供产品设计及装饰画快题方案，累计服务学生<strong>百余人次</strong>。'],eb:['Designed inflatable products from use cases and dimensions to form exploration. Produced <strong>50+ sketches</strong> and helped bring <strong>10+ products</strong> into production.','Refined details around materials and manufacturing. Supported concept sketching and design exercises for over 100 student sessions.'],detail:2}
];
const projects=[
{title:'具身智能 · 方案可视化',en:'Embodied intelligence · Visual solutions',tag:'需求分析 / 信息架构 / 方案设计',et:'REQUIREMENTS / INFORMATION / SOLUTIONS',overview:'围绕工业人形机器人数采与产教融合场景，将复杂业务和技术信息转化为清晰的产品内容。',eo:'Translate complex industrial humanoid data collection and education scenarios into clear product content.',duty:'协同业务与技术团队拆解数采流程，设计数据采集示意 UI，并参与具身智能产业学院工程设计方案与展示内容交付。',ed:'Worked with business and engineering teams to clarify data collection workflows, create UI diagrams and deliver engineering and presentation materials.',result:'30+',caption:'张数据采集示意 UI',ec:'data collection UI diagrams',number:'01',svg:'<rect x="61" y="12" width="48" height="32" rx="9"/><path d="M72 27h5m15 0h5M70 44v10m30-10v10"/><rect x="50" y="54" width="70" height="42" rx="8"/><path d="M50 63L29 84l13 13m78-34 21 21-13 13M68 96v19m34-19v19M60 115h17m17 0h17M68 69h35M68 79h20"/><circle cx="85" cy="74" r="64" stroke-dasharray="3 6"/>'},
{title:'产教业务 · 内容体系升级',en:'Industry–education · Content system',tag:'业务梳理 / 视觉表达 / 展厅落地',et:'BUSINESS / VISUAL DESIGN / EXHIBITION',overview:'围绕产教业务模式、解决方案与产品能力，重新组织业务画册和产品内容的信息层级。',eo:'Reorganized business brochures and product information around industry–education solutions and capabilities.',duty:'通过流程图、产品架构和场景化展示建立内容结构；产教机器人图鉴获采纳，落地南山智园优必选展厅。',ed:'Built a visual hierarchy through flowcharts, product architecture and contextual presentation. The robot catalog was adopted for the Nanshan Intelligence Park showroom.',result:'100+',caption:'项专项展示物料¹',ec:'presentation assets¹',number:'02',svg:'<path d="M30 26h100v80H30zM40 16h100v80M50 6h100v80"/><path d="M43 43h39v24H43zM92 44h24m-24 9h24m-24 9h16M43 81h73m-73 9h50"/><path d="m60 67 10-14 12 14"/>'},
{title:'气模产品 · 从草图到量产',en:'Inflatable products · Sketch to production',tag:'工业设计 / 造型推演 / 材料与工艺',et:'INDUSTRIAL DESIGN / FORM / MATERIALS',overview:'针对产品用途与使用场景展开设计，将概念草图转化为可落地的气模产品。',eo:'Developed inflatable products around intended uses and scenarios, taking early concepts toward manufacture.',duty:'负责尺寸、造型和结构关系的前期策划，完成 50+ 份概念草图与手绘稿，结合材料、工艺优化产品细节。',ed:'Planned dimensions, form and structure; produced 50+ concept sketches and refined details for materials and manufacturing.',result:'10+',caption:'款产品落地量产',ec:'products brought to production',number:'03',svg:'<path d="M43 101V57q0-32 23-32h36q23 0 23 32v44zM57 101V59q0-18 13-18h27q14 0 14 18v42M43 84h14m54 0h14"/><path d="M24 108h125M27 24v77m-5-73 5-5 5 5m-10 68 5 5 5-5M45 13h79m-75-5-5 5 5 5m71-10 5 5-5 5" stroke-dasharray="2 3"/>'}
];
const creations=[['✎','设计手绘','50+ 份概念草图与手绘稿<br>以线条探索造型与结构','查看手绘','Design sketching','50+ concept sketches<br>Exploring form and structure','View sketches',9],['⌘','设计工具箱','从三维建模到界面原型<br>贯穿产品设计的表达工具','查看技能','Design toolkit','From 3D modeling to UI prototypes<br>Tools for product expression','View skills',4],['↗','项目协同','需求分析、方案策划<br>跨部门沟通与交付落地','查看实践','Project coordination','Requirements and planning<br>Cross-functional delivery','View practice',5],['◎','教育背景','合肥大学 · 卓越工程师计划<br>工业设计本科 / 设计硕士','查看教育经历','Education','Hefei University<br>Industrial design / Design','View education',6],['✧','设计荣誉','中国包装创意设计大赛<br>安徽省工业设计大赛','查看获奖','Design awards','China Packaging Creative Design Competition<br>Anhui Industrial Design Competition','View awards',7],['＋','AI 辅助工作流','探索 AI 工具在学习、设计<br>与日常工作中的应用','查看工具','AI-assisted workflow','Exploring AI tools for learning,<br>design and everyday work','View tools',8]];
const extra=[
['招聘流程与沟通实践','Recruitment & communication','<p>特维沃（上海）智能科技有限公司 · 2025.12—2026.02</p><p>通过招聘平台、内推和行业渠道寻访候选人，负责初面评估、能力核验与意向沟通，并组织初试、复试与终面。</p><p>日均筛选简历 300+ 份，独立初面 20 余场，组织各类面试 50 余场。</p>','<p>Teweiwo (Shanghai) · Dec 2025–Feb 2026</p><p>Sourced candidates, evaluated skills and intentions, and coordinated initial, follow-up and final interviews. Screened 300+ résumés daily, conducted 20+ initial interviews and organized 50+ interviews.</p>'],
['设计工具箱','Design toolkit','<h3>三维建模与渲染</h3><div class="chips"><span>Rhino 犀牛</span><span>KeyShot</span><span>CAD</span><span>SolidWorks</span></div><h3>视觉与交互设计</h3><div class="chips"><span>Illustrator</span><span>Photoshop</span><span>Figma</span><span>墨刀</span></div>','<h3>3D modeling & rendering</h3><div class="chips"><span>Rhino</span><span>KeyShot</span><span>CAD</span><span>SolidWorks</span></div><h3>Visual & interaction design</h3><div class="chips"><span>Illustrator</span><span>Photoshop</span><span>Figma</span><span>MockingBot</span></div>'],
['从需求对接到交付落地','From requirements to delivery','<p>在优必选实习期间，承接 CDCC 大会分论坛、EPG 大会等行业活动，围绕业务目标、受众和展示场景制定视觉与内容呈现方案。</p><p>协调相关团队推进主视觉、海报、展板等 10+ 项物料交付。</p>','<p>During the UBTECH internship, planned visuals and content for CDCC and EPG events around business goals, audiences and presentation contexts.</p><p>Coordinated 10+ assets including key visuals, posters and exhibition boards.</p>'],
['教育背景','Education','<h3>2026.09—2029.06 · 设计 / 硕士</h3><p>合肥大学（卓越工程师计划）。2029.06 为预计毕业时间。硕士招生考试初试第 5 名，综合成绩第 3 名。</p><h3>2019.09—2023.06 · 工业设计 / 本科</h3><p>合肥大学（卓越工程师计划）。核心课程：工业设计史、产品设计原理、人机工程学、产品交互设计、设计心理学、材料与工艺、产品改良设计。</p><h3>校园实践</h3><p>班级宣传委员，策划宣传活动 10+ 场；大学生就业创业协会会长，带领 20 人团队开展创业实践项目。</p>','<h3>Sep 2026–Jun 2029 · Master’s in Design</h3><p>Hefei University, Excellent Engineer Program. Expected graduation: June 2029. Ranked 5th in the initial entrance exam and 3rd overall.</p><h3>Sep 2019–Jun 2023 · Bachelor’s in Industrial Design</h3><p>Hefei University. Studies included ergonomics, interaction design, design psychology, materials and manufacturing.</p><h3>Campus experience</h3><p>Organized 10+ publicity events and led a 20-member entrepreneurship association team.</p>'],
['设计荣誉','Design awards','<h3>2023 · 中国包装创意设计大赛</h3><p>三等奖、优秀奖</p><h3>2022 · 中国包装创意设计大赛</h3><p>三等奖、优秀奖</p><h3>安徽省工业设计大赛「镜湖杯」</h3><p>优秀奖</p>','<h3>2023 · China Packaging Creative Design Competition</h3><p>Third Prize & Excellence Award</p><h3>2022 · China Packaging Creative Design Competition</h3><p>Third Prize & Excellence Award</p><h3>Anhui Industrial Design Competition · Jinghu Cup</h3><p>Excellence Award</p>'],
['AI 与协作工具','AI & collaboration tools','<p>简历中列出的日常办公及 AI 工具：</p><div class="chips"><span>WPS</span><span>飞书</span><span>ChatGPT</span><span>Kimi</span><span>DeepSeek</span><span>Claude Code</span><span>Codex</span><span>豆包</span></div>','<p>Office and AI tools listed in the résumé:</p><div class="chips"><span>WPS</span><span>Feishu</span><span>ChatGPT</span><span>Kimi</span><span>DeepSeek</span><span>Claude Code</span><span>Codex</span><span>Doubao</span></div>']];
let english=false;const $=s=>document.querySelector(s);const dialog=$('#detail');
function render(){ $('#experience').innerHTML=experiences.map(x=>`<article class="experience"><div class="experience-top"><div><h3>${english?x.en:x.name}</h3><p class="role">${english?x.er:x.role}</p></div><time class="date">${x.date}</time></div><ul>${(english?x.eb:x.bullets).map(s=>`<li>${s}</li>`).join('')}</ul><div class="detail-row"><button class="text-button" data-detail="${x.detail}">${english?'View details':'查看详情'} ↗</button></div></article>`).join('');
$('#project-grid').innerHTML=projects.map((x,i)=>`<article class="project"><div class="project-art"><svg viewBox="0 0 170 135" aria-hidden="true">${x.svg}</svg><span class="art-caption">${english?'CONCEPT DIAGRAM':'概念示意 · 非项目原图'} / ${x.number}</span></div><div class="project-content"><h3>${english?x.en:x.title}</h3><span class="tag">${english?x.et:x.tag}</span><h4>${english?'OVERVIEW':'项目概述'}</h4><p>${english?x.eo:x.overview}</p><h4>${english?'MY CONTRIBUTION':'项目职责'}</h4><p>${english?x.ed:x.duty}</p><div class="result"><strong>${x.result}</strong><span>${english?x.ec:x.caption}</span></div>${i===1?`<p style="font-size:10px;margin-top:6px">${english?'¹ Total presentation assets across the internship.':'¹ 为该实习期间专项展示物料总量。'}</p>`:''}<button class="text-button" data-detail="${i}">${english?'Explore project':'查看项目详情'} ↗</button></div></article>`).join('');
$('#creation-grid').innerHTML=creations.map(x=>`<article class="creation"><div class="creation-icon" aria-hidden="true">${x[0]}</div><h3>${x[english?4:1]}</h3><p>${x[english?5:2]}</p><button class="text-button" data-detail="${x[7]}">${x[english?6:3]} ↗</button></article>`).join('');}
function showDetail(id){if(id===9){openSketchGallery();return;}dialog.classList.remove('sketch-dialog');let content;if(id<3){let p=projects[id];content=`<span class="eyebrow">PROJECT / ${p.number}</span><h2>${english?p.en:p.title}</h2><h3>${english?'Overview':'项目概述'}</h3><p>${english?p.eo:p.overview}</p><h3>${english?'Contribution':'我的职责'}</h3><p>${english?p.ed:p.duty}</p><h3>${english?'Recorded outcome':'简历记录的成果'}</h3><p><strong>${p.result}</strong> ${english?p.ec:p.caption}</p><p>${english?'This case summary is based on the résumé. The illustrations are conceptual diagrams, not original project deliverables.':'本页依据简历整理；封面线稿为概念示意，非项目原始交付图。'}${id===1?(english?' The 100+ assets refer to the total internship output.':'100+ 项为实习期间专项展示物料总量。'):''}</p>`}else{const x=extra[id-3];content=`<span class="eyebrow">PERSONAL COLLECTION</span><h2>${x[english?1:0]}</h2>${x[english?3:2]}`}$('#detail-body').innerHTML=content;dialog.showModal();document.body.style.overflow='hidden'}
document.addEventListener('click',e=>{const b=e.target.closest('[data-detail]');if(b)showDetail(Number(b.dataset.detail))});$('.close').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});dialog.addEventListener('close',()=>document.body.style.overflow='');
$('.menu').onclick=()=>{const open=$('nav').classList.toggle('open');$('.menu').setAttribute('aria-expanded',open);$('.menu').setAttribute('aria-label',open?'关闭导航':'打开导航')};document.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',()=>{$('nav').classList.remove('open');$('.menu').setAttribute('aria-expanded','false')}));
const observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting)document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.hash==='#'+e.target.id))},{rootMargin:'-20% 0px -65% 0px'});document.querySelectorAll('main>section').forEach(s=>observer.observe(s));
document.querySelectorAll('[data-en]').forEach(e=>e.dataset.zh=e.innerHTML);$('#language').onclick=()=>{english=!english;document.documentElement.lang=english?'en':'zh-CN';$('#language').textContent=english?'EN / 中':'中 / EN';document.querySelectorAll('[data-en]').forEach(e=>e.innerHTML=e.dataset[english?'en':'zh']);const labels=english?['Home','Experience','Projects','Collection','Contact']:['首页','工作经历','工作项目','作品集','联系我'];document.querySelectorAll('nav a').forEach((e,i)=>e.textContent=labels[i]);document.querySelectorAll('.section-note').forEach(e=>e.hidden=english);$('.hero-bottom>a').innerHTML=english?'Explore <span>↓</span>':'向下探索 <span>↓</span>';$('.hero-bottom>span:last-child').textContent=english?'THINK CLEARLY. DESIGN TANGIBLY.':'以思考为起点，以落地为目标';$('footer>span').textContent=english?'© 2026 Guoqing Zhou · From ideas to reality':'© 2026 周国庆 · 以设计连接想法与现实';render()};
$('#copy-email').onclick=async()=>{try{await navigator.clipboard.writeText('zgq67890@163.com');$('#toast').textContent=english?'Email copied':'邮箱已复制'}catch{$('#toast').textContent=english?'Please copy: zgq67890@163.com':'请复制：zgq67890@163.com'}$('#toast').classList.add('visible');setTimeout(()=>$('#toast').classList.remove('visible'),3000)};render();

